# Generated by Django 5.2 on 2025-09-08 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='food_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.foodtype'),
        ),
    ]
