# Generated by Django 5.2 on 2025-09-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_remove_restaurant_menu_card_image_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dishes',
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='dishes', to='restaurants.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dish',
            name='food_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='restaurants.foodtype'),
        ),
    ]
