# Generated by Django 5.2 on 2025-09-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_dish_image_remove_menu_dishes_dish_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, related_name='dishes', to='restaurants.menu'),
        ),
    ]
