# services:
#   postgres:
#     image: postgres:alpine
#     container_name: postgres
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#       - PGDATA=/var/lib/postgresql/data/pgdata
#     ports:
#       - 5432:5432
#     volumes:
#       - ./postgres/pgdata/:var/lib/postgresql/data
#     restart: on-failure